--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: 
  name: helm-clusterrole
rules: 
  - apiGroups: 
      - ""
    resources: 
      - pods/portforward
    verbs: 
      - create
  - apiGroups: 
      - ""
    resources: 
      - pods
      - services
      - secrets
      - namespaces
    verbs: 
      - list
      - get
      - create
      - update
  - apiGroups: 
      - apps
    resources: 
      - deployments
      - replicasets
    verbs: 
      - get
      - list
      - create
