apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: helm-rolebinding_production
  namespace: podtato-head-production
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: helm-clusterrole
subjects:
  - kind: ServiceAccount
    name: helm
    namespace: keptn-jes
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: helm-rolebinding_qa
  namespace: podtato-head-qa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: helm-clusterrole
subjects:
  - kind: ServiceAccount
    name: helm
    namespace: keptn-jes